name: recipe_daily
description: "An app that suggests recipes and calculates calories automatically."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  
  # UI Components
  cupertino_icons: ^1.0.8

  # Flutter Icon
  flutter_launcher_icons: ^0.14.4

  # Firebase Packages
  firebase_core: ^4.2.0
  firebase_auth: ^6.1.1
  cloud_firestore: ^6.0.3
  
  # Email Sending
  mailer: ^6.5.0

  # Authentication
  google_sign_in: ^6.2.0

  # State Management
  provider: ^6.1.1

  # HTTP and Local Storage
  http: ^1.5.0
  shared_preferences: ^2.1.1

  # Storage
  sqflite: ^2.4.1
  path: ^1.9.1 # Path utilities for SQLite
  path_provider: ^2.1.5 # Get application documents directory

  # Image and Video Handling
  image_picker: ^1.0.7 
  video_player: ^2.8.2     
  cached_network_image: ^3.3.1  
  flutter_cache_manager: ^3.3.1

  # Date and Time Formatting for comments
  timeago: ^3.7.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/data/calories.json

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-Italic.ttf
          style: italic

flutter_icons:
  android: true
  image_path: "assets/icons/app_icon.png"
  adaptive_icon_foreground: "assets/icon_foreground.png"

